version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: conventions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: toutou11/springboot-backend-app:latest
    # OU si tu veux build depuis source :
    # build: ./back
    # dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/conventions
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${PGPASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      FILE_UPLOAD_DIR: /data/uploads
      SERVER_URL: https://ton-backend.up.railway.app
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    volumes:
      - uploads_volume:/data/uploads

  frontend:
    image: toutou11/angular-frontend-app:latest
    # OU build depuis source :
    # build: ./front
    # dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      API_URL: https://ton-backend.up.railway.app
    depends_on:
      - backend

volumes:
  postgres_data:
  uploads_volume: